# Ansi Default

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "dracula"


# ========= border =========
file_panel_border = "8"
sidebar_border = "8"
footer_border = "8"

# ========= Border Active =========
file_panel_border_active = "3"
sidebar_border_active = "9"
footer_border_active = "2"
modal_border_active = "6"

# ========= Background (bg) =========
full_screen_bg = "0"
file_panel_bg = "0"
sidebar_bg = "0"
footer_bg = "0"
modal_bg = "0"

# ========= Foreground (fg) =========
full_screen_fg = "7"
file_panel_fg = "7"
sidebar_fg = "7"
footer_fg = "7"
modal_fg = "7"

# ========= Special Color =========
cursor = "3"
correct = "2"
error = "1"
hint = "6"
cancel = "1"
gradient_color = ["4", "6"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "2"
file_panel_top_path = "3"
file_panel_item_selected_fg = "6"
file_panel_item_selected_bg = "8"

# ========= Sidebar Special Items =========
sidebar_title = "6"
sidebar_item_selected_fg = "6"
sidebar_item_selected_bg = "8"
sidebar_divider = "8"

# ========= Modal Special Items =========
modal_cancel_fg = "0"
modal_cancel_bg = "1"

modal_confirm_fg = "0"
modal_confirm_bg = "6"

# ========= Help Menu =========
help_menu_hotkey = "6"
help_menu_title = "1"
